name: insurance
channels:
  - conda-forge  # обязательно первый!
  - defaults
dependencies:
  - python=3.11
  - numpy=1.24.3
  - scipy=1.10.1
  - scikit-learn=1.3.0 # Минимальная с TargetEncoder  
  - catboost=1.2.7
  - py-xgboost=3.1.3
  - lightgbm=4.6.0
  - imbalanced-learn=0.11.0
  - pandas=2.3.3
  - matplotlib=3.10.8
  - seaborn=0.13.2
  - jupyterlab=4.0.0
  - statsmodels
  - tensorflow=2.15.0
  - pip